# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_RenderingPanel.ui'
#
# Created: Sun Jan 03 10:44:46 2010
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_RenderingPanel(object):
    def setupUi(self, RenderingPanel):
        RenderingPanel.setObjectName("RenderingPanel")
        RenderingPanel.resize(250, 874)
        RenderingPanel.setMinimumSize(QtCore.QSize(250, 731))
        RenderingPanel.setMaximumSize(QtCore.QSize(250, 15000))
        self.verticalLayout = QtGui.QVBoxLayout(RenderingPanel)
        self.verticalLayout.setObjectName("verticalLayout")
        self.previewGB = QtGui.QGroupBox(RenderingPanel)
        self.previewGB.setMinimumSize(QtCore.QSize(230, 0))
        self.previewGB.setMaximumSize(QtCore.QSize(230, 16777215))
        self.previewGB.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.previewGB.setObjectName("previewGB")
        self.vboxlayout = QtGui.QVBoxLayout(self.previewGB)
        self.vboxlayout.setSpacing(6)
        self.vboxlayout.setContentsMargins(15, -1, -1, -1)
        self.vboxlayout.setObjectName("vboxlayout")
        self.previewImg = QtGui.QLabel(self.previewGB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previewImg.sizePolicy().hasHeightForWidth())
        self.previewImg.setSizePolicy(sizePolicy)
        self.previewImg.setMinimumSize(QtCore.QSize(180, 180))
        self.previewImg.setMaximumSize(QtCore.QSize(180, 180))
        self.previewImg.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.previewImg.setAutoFillBackground(False)
        self.previewImg.setAlignment(QtCore.Qt.AlignCenter)
        self.previewImg.setObjectName("previewImg")
        self.vboxlayout.addWidget(self.previewImg)
        self.verticalLayout.addWidget(self.previewGB)
        self.groupBox = QtGui.QGroupBox(RenderingPanel)
        self.groupBox.setMinimumSize(QtCore.QSize(230, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(230, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.vboxlayout1 = QtGui.QVBoxLayout(self.groupBox)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.previewCB = QtGui.QCheckBox(self.groupBox)
        self.previewCB.setChecked(True)
        self.previewCB.setObjectName("previewCB")
        self.vboxlayout1.addWidget(self.previewCB)
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.vboxlayout2 = QtGui.QVBoxLayout()
        self.vboxlayout2.setObjectName("vboxlayout2")
        self.formatL_2 = QtGui.QLabel(self.groupBox)
        self.formatL_2.setEnabled(True)
        self.formatL_2.setMinimumSize(QtCore.QSize(70, 0))
        self.formatL_2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.formatL_2.setObjectName("formatL_2")
        self.vboxlayout2.addWidget(self.formatL_2)
        self.aspectRatioL = QtGui.QLabel(self.groupBox)
        self.aspectRatioL.setEnabled(False)
        self.aspectRatioL.setMinimumSize(QtCore.QSize(110, 0))
        self.aspectRatioL.setMaximumSize(QtCore.QSize(70, 16777215))
        self.aspectRatioL.setObjectName("aspectRatioL")
        self.vboxlayout2.addWidget(self.aspectRatioL)
        self.formatL = QtGui.QLabel(self.groupBox)
        self.formatL.setEnabled(False)
        self.formatL.setMinimumSize(QtCore.QSize(110, 0))
        self.formatL.setMaximumSize(QtCore.QSize(110, 16777215))
        self.formatL.setObjectName("formatL")
        self.vboxlayout2.addWidget(self.formatL)
        self.hboxlayout.addLayout(self.vboxlayout2)
        self.vboxlayout3 = QtGui.QVBoxLayout()
        self.vboxlayout3.setObjectName("vboxlayout3")
        self.ribCB = QtGui.QComboBox(self.groupBox)
        self.ribCB.setObjectName("ribCB")
        self.vboxlayout3.addWidget(self.ribCB)
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.aspectRatioEdit = QtGui.QLineEdit(self.groupBox)
        self.aspectRatioEdit.setEnabled(False)
        self.aspectRatioEdit.setMinimumSize(QtCore.QSize(46, 0))
        self.aspectRatioEdit.setMaximumSize(QtCore.QSize(46, 16777215))
        self.aspectRatioEdit.setObjectName("aspectRatioEdit")
        self.hboxlayout1.addWidget(self.aspectRatioEdit)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout1.addItem(spacerItem)
        self.vboxlayout3.addLayout(self.hboxlayout1)
        self.hboxlayout2 = QtGui.QHBoxLayout()
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.formatWidthSB = QtGui.QSpinBox(self.groupBox)
        self.formatWidthSB.setEnabled(False)
        self.formatWidthSB.setObjectName("formatWidthSB")
        self.hboxlayout2.addWidget(self.formatWidthSB)
        self.formatHeightSB = QtGui.QSpinBox(self.groupBox)
        self.formatHeightSB.setEnabled(False)
        self.formatHeightSB.setObjectName("formatHeightSB")
        self.hboxlayout2.addWidget(self.formatHeightSB)
        self.vboxlayout3.addLayout(self.hboxlayout2)
        self.hboxlayout.addLayout(self.vboxlayout3)
        spacerItem1 = QtGui.QSpacerItem(16, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem1)
        self.vboxlayout1.addLayout(self.hboxlayout)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(RenderingPanel)
        self.groupBox_2.setMinimumSize(QtCore.QSize(230, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(230, 16777215))
        self.groupBox_2.setObjectName("groupBox_2")
        self.vboxlayout4 = QtGui.QVBoxLayout(self.groupBox_2)
        self.vboxlayout4.setObjectName("vboxlayout4")
        self.hboxlayout3 = QtGui.QHBoxLayout()
        self.hboxlayout3.setObjectName("hboxlayout3")
        self.vboxlayout5 = QtGui.QVBoxLayout()
        self.vboxlayout5.setObjectName("vboxlayout5")
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setMinimumSize(QtCore.QSize(110, 0))
        self.label_12.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_12.setObjectName("label_12")
        self.vboxlayout5.addWidget(self.label_12)
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setMinimumSize(QtCore.QSize(110, 0))
        self.label_3.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_3.setObjectName("label_3")
        self.vboxlayout5.addWidget(self.label_3)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setMinimumSize(QtCore.QSize(110, 0))
        self.label_4.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_4.setObjectName("label_4")
        self.vboxlayout5.addWidget(self.label_4)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setMinimumSize(QtCore.QSize(110, 0))
        self.label_5.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_5.setObjectName("label_5")
        self.vboxlayout5.addWidget(self.label_5)
        self.hboxlayout3.addLayout(self.vboxlayout5)
        self.vboxlayout6 = QtGui.QVBoxLayout()
        self.vboxlayout6.setObjectName("vboxlayout6")
        self.hboxlayout4 = QtGui.QHBoxLayout()
        self.hboxlayout4.setObjectName("hboxlayout4")
        self.samplesXSB = QtGui.QSpinBox(self.groupBox_2)
        self.samplesXSB.setObjectName("samplesXSB")
        self.hboxlayout4.addWidget(self.samplesXSB)
        self.samplesYSB = QtGui.QSpinBox(self.groupBox_2)
        self.samplesYSB.setObjectName("samplesYSB")
        self.hboxlayout4.addWidget(self.samplesYSB)
        self.vboxlayout6.addLayout(self.hboxlayout4)
        self.filterCB = QtGui.QComboBox(self.groupBox_2)
        self.filterCB.setMinimumSize(QtCore.QSize(100, 0))
        self.filterCB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.filterCB.setObjectName("filterCB")
        self.vboxlayout6.addWidget(self.filterCB)
        self.hboxlayout5 = QtGui.QHBoxLayout()
        self.hboxlayout5.setObjectName("hboxlayout5")
        self.filterWidthXSB = QtGui.QSpinBox(self.groupBox_2)
        self.filterWidthXSB.setObjectName("filterWidthXSB")
        self.hboxlayout5.addWidget(self.filterWidthXSB)
        self.filterWidthYSB = QtGui.QSpinBox(self.groupBox_2)
        self.filterWidthYSB.setObjectName("filterWidthYSB")
        self.hboxlayout5.addWidget(self.filterWidthYSB)
        self.vboxlayout6.addLayout(self.hboxlayout5)
        self.shadingRateEdit = QtGui.QLineEdit(self.groupBox_2)
        self.shadingRateEdit.setMinimumSize(QtCore.QSize(46, 0))
        self.shadingRateEdit.setMaximumSize(QtCore.QSize(46, 16777215))
        self.shadingRateEdit.setObjectName("shadingRateEdit")
        self.vboxlayout6.addWidget(self.shadingRateEdit)
        self.hboxlayout3.addLayout(self.vboxlayout6)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout3.addItem(spacerItem2)
        self.vboxlayout4.addLayout(self.hboxlayout3)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(RenderingPanel)
        self.groupBox_3.setMinimumSize(QtCore.QSize(230, 0))
        self.groupBox_3.setMaximumSize(QtCore.QSize(230, 16777215))
        self.groupBox_3.setObjectName("groupBox_3")
        self.vboxlayout7 = QtGui.QVBoxLayout(self.groupBox_3)
        self.vboxlayout7.setObjectName("vboxlayout7")
        self.hboxlayout6 = QtGui.QHBoxLayout()
        self.hboxlayout6.setObjectName("hboxlayout6")
        self.vboxlayout8 = QtGui.QVBoxLayout()
        self.vboxlayout8.setObjectName("vboxlayout8")
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setMinimumSize(QtCore.QSize(110, 0))
        self.label_2.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_2.setObjectName("label_2")
        self.vboxlayout8.addWidget(self.label_2)
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setMinimumSize(QtCore.QSize(110, 0))
        self.label_7.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_7.setObjectName("label_7")
        self.vboxlayout8.addWidget(self.label_7)
        self.label_8 = QtGui.QLabel(self.groupBox_3)
        self.label_8.setMinimumSize(QtCore.QSize(110, 0))
        self.label_8.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_8.setObjectName("label_8")
        self.vboxlayout8.addWidget(self.label_8)
        self.label_9 = QtGui.QLabel(self.groupBox_3)
        self.label_9.setMinimumSize(QtCore.QSize(110, 0))
        self.label_9.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_9.setObjectName("label_9")
        self.vboxlayout8.addWidget(self.label_9)
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        self.label_10.setMinimumSize(QtCore.QSize(110, 0))
        self.label_10.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_10.setObjectName("label_10")
        self.vboxlayout8.addWidget(self.label_10)
        self.label_11 = QtGui.QLabel(self.groupBox_3)
        self.label_11.setMinimumSize(QtCore.QSize(110, 0))
        self.label_11.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_11.setObjectName("label_11")
        self.vboxlayout8.addWidget(self.label_11)
        self.hboxlayout6.addLayout(self.vboxlayout8)
        self.vboxlayout9 = QtGui.QVBoxLayout()
        self.vboxlayout9.setObjectName("vboxlayout9")
        self.surfaceCB = QtGui.QComboBox(self.groupBox_3)
        self.surfaceCB.setMinimumSize(QtCore.QSize(100, 0))
        self.surfaceCB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.surfaceCB.setObjectName("surfaceCB")
        self.vboxlayout9.addWidget(self.surfaceCB)
        self.displacementCB = QtGui.QComboBox(self.groupBox_3)
        self.displacementCB.setMinimumSize(QtCore.QSize(100, 0))
        self.displacementCB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.displacementCB.setObjectName("displacementCB")
        self.vboxlayout9.addWidget(self.displacementCB)
        self.atmosphereCB = QtGui.QComboBox(self.groupBox_3)
        self.atmosphereCB.setMinimumSize(QtCore.QSize(100, 0))
        self.atmosphereCB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.atmosphereCB.setObjectName("atmosphereCB")
        self.vboxlayout9.addWidget(self.atmosphereCB)
        self.interiorCB = QtGui.QComboBox(self.groupBox_3)
        self.interiorCB.setMinimumSize(QtCore.QSize(100, 0))
        self.interiorCB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.interiorCB.setObjectName("interiorCB")
        self.vboxlayout9.addWidget(self.interiorCB)
        self.exteriorCB = QtGui.QComboBox(self.groupBox_3)
        self.exteriorCB.setMinimumSize(QtCore.QSize(100, 0))
        self.exteriorCB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.exteriorCB.setObjectName("exteriorCB")
        self.vboxlayout9.addWidget(self.exteriorCB)
        self.imagerCB = QtGui.QComboBox(self.groupBox_3)
        self.imagerCB.setMinimumSize(QtCore.QSize(100, 0))
        self.imagerCB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.imagerCB.setObjectName("imagerCB")
        self.vboxlayout9.addWidget(self.imagerCB)
        self.hboxlayout6.addLayout(self.vboxlayout9)
        self.vboxlayout7.addLayout(self.hboxlayout6)
        self.verticalLayout.addWidget(self.groupBox_3)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)

        self.retranslateUi(RenderingPanel)
        QtCore.QObject.connect(self.previewCB, QtCore.SIGNAL("toggled(bool)"), self.previewGB.setEnabled)
        QtCore.QObject.connect(self.previewCB, QtCore.SIGNAL("toggled(bool)"), self.aspectRatioEdit.setDisabled)
        QtCore.QObject.connect(self.previewCB, QtCore.SIGNAL("toggled(bool)"), self.formatHeightSB.setDisabled)
        QtCore.QObject.connect(self.previewCB, QtCore.SIGNAL("toggled(bool)"), self.formatWidthSB.setDisabled)
        QtCore.QObject.connect(self.previewCB, QtCore.SIGNAL("toggled(bool)"), self.aspectRatioL.setDisabled)
        QtCore.QObject.connect(self.previewCB, QtCore.SIGNAL("toggled(bool)"), self.formatL.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(RenderingPanel)

    def retranslateUi(self, RenderingPanel):
        RenderingPanel.setWindowTitle(QtGui.QApplication.translate("RenderingPanel", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.previewGB.setTitle(QtGui.QApplication.translate("RenderingPanel", "Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.previewImg.setText(QtGui.QApplication.translate("RenderingPanel", "Preview Image", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("RenderingPanel", "Image", None, QtGui.QApplication.UnicodeUTF8))
        self.previewCB.setText(QtGui.QApplication.translate("RenderingPanel", "Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.formatL_2.setText(QtGui.QApplication.translate("RenderingPanel", "Rib:", None, QtGui.QApplication.UnicodeUTF8))
        self.aspectRatioL.setText(QtGui.QApplication.translate("RenderingPanel", "Aspect Ratio:", None, QtGui.QApplication.UnicodeUTF8))
        self.formatL.setText(QtGui.QApplication.translate("RenderingPanel", "Format:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("RenderingPanel", "Quality", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("RenderingPanel", "Samples:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("RenderingPanel", "Filter:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("RenderingPanel", "Filter Width:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("RenderingPanel", "Shading Rate:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("RenderingPanel", "Shaders", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("RenderingPanel", "Surface:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("RenderingPanel", "Displacement:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("RenderingPanel", "Atmosphere:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("RenderingPanel", "Interior:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("RenderingPanel", "Exterior:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("RenderingPanel", "Imager:", None, QtGui.QApplication.UnicodeUTF8))

