##################################################################################
#
#  Shaderlink - A RenderMan Shader Authoring Toolkit 
#  http://libe.ocracy.org/shaderlink.html
#  2010 Libero Spagnolini (libero.spagnolini@gmail.com)
#
##################################################################################

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\gui\modifier\ui_ColorPropertyModifier.ui'
#
# Created: Sat Nov 01 11:06:12 2008
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_ColorPropertyModifier(object):
    def setupUi(self, ColorPropertyModifier):
        ColorPropertyModifier.setObjectName("ColorPropertyModifier")
        ColorPropertyModifier.resize(232, 114)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ColorPropertyModifier.sizePolicy().hasHeightForWidth())
        ColorPropertyModifier.setSizePolicy(sizePolicy)
        ColorPropertyModifier.setMinimumSize(QtCore.QSize(232, 114))
        ColorPropertyModifier.setMaximumSize(QtCore.QSize(232, 114))
        self.vboxlayout = QtGui.QVBoxLayout(ColorPropertyModifier)
        self.vboxlayout.setSpacing(0)
        self.vboxlayout.setMargin(0)
        self.vboxlayout.setObjectName("vboxlayout")
        self.propGroupBox = QtGui.QGroupBox(ColorPropertyModifier)
        self.propGroupBox.setObjectName("propGroupBox")
        self.hboxlayout = QtGui.QHBoxLayout(self.propGroupBox)
        self.hboxlayout.setObjectName("hboxlayout")
        self.vboxlayout1 = QtGui.QVBoxLayout()
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.redLabel = QtGui.QLabel(self.propGroupBox)
        self.redLabel.setMinimumSize(QtCore.QSize(7, 15))
        self.redLabel.setMaximumSize(QtCore.QSize(7, 15))
        self.redLabel.setObjectName("redLabel")
        self.hboxlayout1.addWidget(self.redLabel)
        self.redEdit = QtGui.QLineEdit(self.propGroupBox)
        self.redEdit.setMinimumSize(QtCore.QSize(50, 20))
        self.redEdit.setMaximumSize(QtCore.QSize(50, 20))
        self.redEdit.setObjectName("redEdit")
        self.hboxlayout1.addWidget(self.redEdit)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout1.addItem(spacerItem)
        self.redSlider = QtGui.QSlider(self.propGroupBox)
        self.redSlider.setMinimumSize(QtCore.QSize(75, 20))
        self.redSlider.setMaximumSize(QtCore.QSize(75, 20))
        self.redSlider.setOrientation(QtCore.Qt.Horizontal)
        self.redSlider.setObjectName("redSlider")
        self.hboxlayout1.addWidget(self.redSlider)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout1.addItem(spacerItem1)
        self.vboxlayout1.addLayout(self.hboxlayout1)
        self.hboxlayout2 = QtGui.QHBoxLayout()
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.greenLabel = QtGui.QLabel(self.propGroupBox)
        self.greenLabel.setMinimumSize(QtCore.QSize(7, 15))
        self.greenLabel.setMaximumSize(QtCore.QSize(7, 15))
        self.greenLabel.setObjectName("greenLabel")
        self.hboxlayout2.addWidget(self.greenLabel)
        self.greenEdit = QtGui.QLineEdit(self.propGroupBox)
        self.greenEdit.setMinimumSize(QtCore.QSize(50, 20))
        self.greenEdit.setMaximumSize(QtCore.QSize(50, 20))
        self.greenEdit.setObjectName("greenEdit")
        self.hboxlayout2.addWidget(self.greenEdit)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout2.addItem(spacerItem2)
        self.greenSlider = QtGui.QSlider(self.propGroupBox)
        self.greenSlider.setMinimumSize(QtCore.QSize(75, 20))
        self.greenSlider.setMaximumSize(QtCore.QSize(75, 20))
        self.greenSlider.setOrientation(QtCore.Qt.Horizontal)
        self.greenSlider.setObjectName("greenSlider")
        self.hboxlayout2.addWidget(self.greenSlider)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout2.addItem(spacerItem3)
        self.vboxlayout1.addLayout(self.hboxlayout2)
        self.hboxlayout3 = QtGui.QHBoxLayout()
        self.hboxlayout3.setObjectName("hboxlayout3")
        self.blueLabel = QtGui.QLabel(self.propGroupBox)
        self.blueLabel.setMinimumSize(QtCore.QSize(7, 15))
        self.blueLabel.setMaximumSize(QtCore.QSize(7, 15))
        self.blueLabel.setObjectName("blueLabel")
        self.hboxlayout3.addWidget(self.blueLabel)
        self.blueEdit = QtGui.QLineEdit(self.propGroupBox)
        self.blueEdit.setMinimumSize(QtCore.QSize(50, 20))
        self.blueEdit.setMaximumSize(QtCore.QSize(50, 20))
        self.blueEdit.setObjectName("blueEdit")
        self.hboxlayout3.addWidget(self.blueEdit)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout3.addItem(spacerItem4)
        self.blueSlider = QtGui.QSlider(self.propGroupBox)
        self.blueSlider.setMinimumSize(QtCore.QSize(75, 20))
        self.blueSlider.setMaximumSize(QtCore.QSize(75, 20))
        self.blueSlider.setOrientation(QtCore.Qt.Horizontal)
        self.blueSlider.setObjectName("blueSlider")
        self.hboxlayout3.addWidget(self.blueSlider)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout3.addItem(spacerItem5)
        self.vboxlayout1.addLayout(self.hboxlayout3)
        self.hboxlayout.addLayout(self.vboxlayout1)
        self.previewImg = QtGui.QLabel(self.propGroupBox)
        self.previewImg.setMinimumSize(QtCore.QSize(60, 80))
        self.previewImg.setMaximumSize(QtCore.QSize(60, 80))
        self.previewImg.setAlignment(QtCore.Qt.AlignCenter)
        self.previewImg.setOpenExternalLinks(True)
        self.previewImg.setObjectName("previewImg")
        self.hboxlayout.addWidget(self.previewImg)
        self.vboxlayout.addWidget(self.propGroupBox)

        self.retranslateUi(ColorPropertyModifier)
        QtCore.QMetaObject.connectSlotsByName(ColorPropertyModifier)

    def retranslateUi(self, ColorPropertyModifier):
        ColorPropertyModifier.setWindowTitle(QtGui.QApplication.translate("ColorPropertyModifier", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.propGroupBox.setTitle(QtGui.QApplication.translate("ColorPropertyModifier", "Color", None, QtGui.QApplication.UnicodeUTF8))
        self.redLabel.setText(QtGui.QApplication.translate("ColorPropertyModifier", "R", None, QtGui.QApplication.UnicodeUTF8))
        self.greenLabel.setText(QtGui.QApplication.translate("ColorPropertyModifier", "G", None, QtGui.QApplication.UnicodeUTF8))
        self.blueLabel.setText(QtGui.QApplication.translate("ColorPropertyModifier", "B", None, QtGui.QApplication.UnicodeUTF8))

