##################################################################################
#
#  Shaderlink - A RenderMan Shader Authoring Toolkit 
#  http://libe.ocracy.org/shaderlink.html
#  2010 Libero Spagnolini (libero.spagnolini@gmail.com)
#
##################################################################################

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\gui\modifier\ui_MatrixPropertyModifier.ui'
#
# Created: Wed Oct 01 22:43:10 2008
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MatrixPropertyModifier(object):
    def setupUi(self, MatrixPropertyModifier):
        MatrixPropertyModifier.setObjectName("MatrixPropertyModifier")
        MatrixPropertyModifier.resize(232, 134)
        MatrixPropertyModifier.setMinimumSize(QtCore.QSize(232, 114))
        MatrixPropertyModifier.setMaximumSize(QtCore.QSize(232, 134))
        self.verticalLayout_2 = QtGui.QVBoxLayout(MatrixPropertyModifier)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.propGroupBox = QtGui.QGroupBox(MatrixPropertyModifier)
        self.propGroupBox.setObjectName("propGroupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.propGroupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridlayout = QtGui.QGridLayout()
        self.gridlayout.setObjectName("gridlayout")
        self.matEdit_0_0 = QtGui.QLineEdit(self.propGroupBox)
        self.matEdit_0_0.setMinimumSize(QtCore.QSize(35, 0))
        self.matEdit_0_0.setMaximumSize(QtCore.QSize(35, 16777215))
        self.matEdit_0_0.setObjectName("matEdit_0_0")
        self.gridlayout.addWidget(self.matEdit_0_0, 0, 0, 1, 1)
        self.matEdit_0_1 = QtGui.QLineEdit(self.propGroupBox)
        self.matEdit_0_1.setMinimumSize(QtCore.QSize(35, 0))
        self.matEdit_0_1.setMaximumSize(QtCore.QSize(35, 16777215))
        self.matEdit_0_1.setObjectName("matEdit_0_1")
        self.gridlayout.addWidget(self.matEdit_0_1, 0, 1, 1, 1)
        self.matEdit_0_2 = QtGui.QLineEdit(self.propGroupBox)
        self.matEdit_0_2.setMinimumSize(QtCore.QSize(35, 0))
        self.matEdit_0_2.setMaximumSize(QtCore.QSize(35, 16777215))
        self.matEdit_0_2.setObjectName("matEdit_0_2")
        self.gridlayout.addWidget(self.matEdit_0_2, 0, 2, 1, 1)
        self.matEdit_0_3 = QtGui.QLineEdit(self.propGroupBox)
        self.matEdit_0_3.setMinimumSize(QtCore.QSize(35, 0))
        self.matEdit_0_3.setMaximumSize(QtCore.QSize(35, 16777215))
        self.matEdit_0_3.setObjectName("matEdit_0_3")
        self.gridlayout.addWidget(self.matEdit_0_3, 0, 3, 1, 1)
        self.matEdit_1_0 = QtGui.QLineEdit(self.propGroupBox)
        self.matEdit_1_0.setMinimumSize(QtCore.QSize(35, 0))
        self.matEdit_1_0.setMaximumSize(QtCore.QSize(35, 16777215))
        self.matEdit_1_0.setObjectName("matEdit_1_0")
        self.gridlayout.addWidget(self.matEdit_1_0, 1, 0, 1, 1)
        self.matEdit_1_1 = QtGui.QLineEdit(self.propGroupBox)
        self.matEdit_1_1.setMinimumSize(QtCore.QSize(35, 0))
        self.matEdit_1_1.setMaximumSize(QtCore.QSize(35, 16777215))
        self.matEdit_1_1.setObjectName("matEdit_1_1")
        self.gridlayout.addWidget(self.matEdit_1_1, 1, 1, 1, 1)
        self.matEdit_1_2 = QtGui.QLineEdit(self.propGroupBox)
        self.matEdit_1_2.setMinimumSize(QtCore.QSize(35, 0))
        self.matEdit_1_2.setMaximumSize(QtCore.QSize(35, 16777215))
        self.matEdit_1_2.setObjectName("matEdit_1_2")
        self.gridlayout.addWidget(self.matEdit_1_2, 1, 2, 1, 1)
        self.matEdit_1_3 = QtGui.QLineEdit(self.propGroupBox)
        self.matEdit_1_3.setMinimumSize(QtCore.QSize(35, 0))
        self.matEdit_1_3.setMaximumSize(QtCore.QSize(35, 16777215))
        self.matEdit_1_3.setObjectName("matEdit_1_3")
        self.gridlayout.addWidget(self.matEdit_1_3, 1, 3, 1, 1)
        self.matEdit_2_0 = QtGui.QLineEdit(self.propGroupBox)
        self.matEdit_2_0.setMinimumSize(QtCore.QSize(35, 0))
        self.matEdit_2_0.setMaximumSize(QtCore.QSize(35, 16777215))
        self.matEdit_2_0.setObjectName("matEdit_2_0")
        self.gridlayout.addWidget(self.matEdit_2_0, 2, 0, 1, 1)
        self.matEdit_2_1 = QtGui.QLineEdit(self.propGroupBox)
        self.matEdit_2_1.setMinimumSize(QtCore.QSize(35, 0))
        self.matEdit_2_1.setMaximumSize(QtCore.QSize(35, 16777215))
        self.matEdit_2_1.setObjectName("matEdit_2_1")
        self.gridlayout.addWidget(self.matEdit_2_1, 2, 1, 1, 1)
        self.matEdit_2_2 = QtGui.QLineEdit(self.propGroupBox)
        self.matEdit_2_2.setMinimumSize(QtCore.QSize(35, 0))
        self.matEdit_2_2.setMaximumSize(QtCore.QSize(35, 16777215))
        self.matEdit_2_2.setObjectName("matEdit_2_2")
        self.gridlayout.addWidget(self.matEdit_2_2, 2, 2, 1, 1)
        self.matEdit_2_3 = QtGui.QLineEdit(self.propGroupBox)
        self.matEdit_2_3.setMinimumSize(QtCore.QSize(35, 0))
        self.matEdit_2_3.setMaximumSize(QtCore.QSize(35, 16777215))
        self.matEdit_2_3.setObjectName("matEdit_2_3")
        self.gridlayout.addWidget(self.matEdit_2_3, 2, 3, 1, 1)
        self.matEdit_3_0 = QtGui.QLineEdit(self.propGroupBox)
        self.matEdit_3_0.setMinimumSize(QtCore.QSize(35, 0))
        self.matEdit_3_0.setMaximumSize(QtCore.QSize(35, 16777215))
        self.matEdit_3_0.setObjectName("matEdit_3_0")
        self.gridlayout.addWidget(self.matEdit_3_0, 3, 0, 1, 1)
        self.matEdit_3_1 = QtGui.QLineEdit(self.propGroupBox)
        self.matEdit_3_1.setMinimumSize(QtCore.QSize(35, 0))
        self.matEdit_3_1.setMaximumSize(QtCore.QSize(35, 16777215))
        self.matEdit_3_1.setObjectName("matEdit_3_1")
        self.gridlayout.addWidget(self.matEdit_3_1, 3, 1, 1, 1)
        self.matEdit_3_2 = QtGui.QLineEdit(self.propGroupBox)
        self.matEdit_3_2.setMinimumSize(QtCore.QSize(35, 0))
        self.matEdit_3_2.setMaximumSize(QtCore.QSize(35, 16777215))
        self.matEdit_3_2.setObjectName("matEdit_3_2")
        self.gridlayout.addWidget(self.matEdit_3_2, 3, 2, 1, 1)
        self.matEdit_3_3 = QtGui.QLineEdit(self.propGroupBox)
        self.matEdit_3_3.setMinimumSize(QtCore.QSize(35, 0))
        self.matEdit_3_3.setMaximumSize(QtCore.QSize(35, 16777215))
        self.matEdit_3_3.setObjectName("matEdit_3_3")
        self.gridlayout.addWidget(self.matEdit_3_3, 3, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridlayout)
        self.verticalLayout_2.addWidget(self.propGroupBox)

        self.retranslateUi(MatrixPropertyModifier)
        QtCore.QMetaObject.connectSlotsByName(MatrixPropertyModifier)

    def retranslateUi(self, MatrixPropertyModifier):
        MatrixPropertyModifier.setWindowTitle(QtGui.QApplication.translate("MatrixPropertyModifier", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.propGroupBox.setTitle(QtGui.QApplication.translate("MatrixPropertyModifier", "Matrix", None, QtGui.QApplication.UnicodeUTF8))

